kind: Application
metadata:
  name: mysql-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bitpoke.github.io/mysql-operator
    chart: mysql-operator
    targetRevision: 0.5.0
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
