apiVersion: v1
kind: Service
metadata:
  name: tp-foyer-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: tp-foyer-backend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8089

---
apiVersion: v1
kind: Service
metadata:
  name: tp-foyer-backend-nodeport
spec:
  type: NodePort
  selector:
    app: tp-foyer-backend
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30089  # Spécifie un port externe
