apiVersion: v1
kind: Service
metadata:
  name: tp-foyer-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: tp-foyer-backend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8089
