apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-app-pg
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-spring-app-pg
  template:
    metadata:
      labels:
        app: my-spring-app-pg
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8089
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          
