apiVersion: v1
kind: Service
metadata:
  name: my-spring-app-pg
spec:
  type: {{ .Values.service.type }}
  selector:
    app: my-spring-app-pg
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8089

---
apiVersion: v1
kind: Service
metadata:
  name: my-spring-app-ala-nodeport
spec:
  type: NodePort
  selector:
    app: my-spring-app-pg
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30089  # Spécifie un port externe
