apiVersion: v1
kind: Service
metadata:
  name: my-spring-app-pg
spec:
  type: {{ .Values.service.type }}
  selector:
    app: my-spring-app-pg
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8089


