# Namespace configuration
namespace: argocd

# PostgreSQL cluster configuration
postgresql:
  clusterName: ha-postgres
  teamId: "ha-team"
  numberOfInstances: 3
  version: "14"
  
  # Database and users
  databases:
    myapp: myapp  # database_name: owner_user
  
  users:
    myapp:
      - createdb
      - login
  
  # Resources
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

# Static storage configuration (NFS)
storage:
  enabled: true
  size: 10Gi
  nfsServer: 192.168.1.53
  nfsPath: /rpool/nfs-share/postgres
  reclaimPolicy: Retain

# Connection pooler
connectionPooler:
  enabled: true
  mode: transaction

# Patroni configuration for HA
patroni:
  synchronous_mode: true
  synchronous_mode_strict: true
  ttl: 30
  loop_wait: 5
  retry_timeout: 8

# Custom passwords (optional)
env:
  PGPASSWORD_MYAPP: "postgres"
