namespace: argocd

postgresql:
  clusterName: ha-postgres
  teamId: "ha-team"
  numberOfInstances: 3
  version: "14"
  
  databases:
    myapp: myapp
  
  users:
    myapp:
      - createdb
      - login
  
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

storage:
  enabled: true
  size: 10Gi
  nfsServer: 192.168.1.53
  nfsPath: /rpool/nfs-share/postgres
  reclaimPolicy: Retain

connectionPooler:
  enabled: true
  mode: transaction

patroni:
  synchronous_mode: true
  synchronous_mode_strict: true
  ttl: 30
  loop_wait: 5
  retry_timeout: 8

env:
  PGPASSWORD_MYAPP: "postgres"
