apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/alachebil/GitOps-Repo.git'
    targetRevision: HEAD
    path: apps/mysql/cluster
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
