apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-angular-app-ala.fullname" . }}
  labels:
    {{- include "my-angular-app-ala.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-angular-app-ala.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-angular-app-ala.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets | default "regcred" }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: API_URL
              value: {{ .Values.apiUrl | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
