apiVersion: v1
kind: Service
metadata:
  name: postgres-ha
  namespace: argocd
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    application: spilo
    cluster-name: postgres-ha
