apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres-ha
  namespace: argocd
spec:
  teamId: "acid"
  volume:
    size: 1Gi
    storageClass: ""
  numberOfInstances: 3
  users:
    postgresuser:  # database owner
      - superuser
      - createdb
  databases:
    mydb: postgresuser
  postgresql:
    version: "14"
  patroni:
    synchronous_mode: true
    synchronous_mode_strict: true
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k8s-worker4
                  - k8s-worker5
                  - k8s-worker6
