{- if .Values.storage.enabled }}
{{- range $i := until (int .Values.postgresql.numberOfInstances) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-{{ $.Values.postgresql.clusterName }}-{{ $i }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: postgres-cluster
    instance: "{{ $i }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.storage.size }}
  storageClassName: ""  # Pour utiliser les PV statiques
  selector:
    matchLabels:
      app: postgres-cluster
      instance: "{{ $i }}"
{{- end }}
{{- end }}
